### PR TITLE
Added null validation when rendering the stars

### PR DESCRIPTION
**Pull request by KiritoDv**
This PR adds a null validation to avoid crashing when used with mods that create worlds for example LostCities which was the mod used to test this change

### CODE REVIEW

**Comment by F0x06** [comment]
Hi, thanks for the PR, devs can you merge this please ? My modpack is affected by a crash when going back from mining dimensions, thanks.

**Comment by st0x0ef** [comment]
Sure

**Comment by F0x06** [comment]
Thanks for the merge ! Do you have an ETA when the version with this fix will be pushed on CurseForge or Modrinth for `1.20.1` ?

**Comment by st0x0ef** [comment]
Thanks for the reminder, I'll push it today or tomorrow

**Pull request merged**
